version: '3.7'
services:
  frontend:
    image: cr.yandex/crpfap56bqr8nkph7d9g/front-places:latest
    env_file:
      - ./.env
    ports:
      - 3005:80
    depends_on:
      - backend
    networks:
      - internet
    restart: unless-stopped

networks:
  internet:
    driver: bridge
