services:
  frontend:
    image: cr.yandex/crpfap56bqr8nkph7d9g/front-places:latest
    build:
      dockerfile: Dockerfile
    env_file:
      - ./.env.production
    ports:
      - 3005:80
    networks:
      - internet
    restart: unless-stopped

networks:
  internet:
    driver: bridge
